[package]
name = "scene-core-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "scene-core"
path = "src/main.rs"

[dependencies]
scene-core-protocol = { path = "../scene-core-protocol" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

